from collections import namedtuple
from enum import Enum


ArgUnpackTypes = Enum('ArgUnpackTypes', 'args kwargs none')
UnaryOpType = Enum('UnaryOp', 'UAdd Invert USub Not')
BoolOpType = Enum('BoolOp', 'And Or')
OperatorType = Enum('Operator', 'Add Div Sub Mod Pow Mult MatMult RShift LShift BitOr BitXOr BitAnd FloorDiv')
ComparisonOpType = Enum('ComparisonOp', 'Eq NotEq Lt LtE Gt GtE Is IsNot In NotIn')

Slice = namedtuple('Subscript', 'first second third')

Dict = namedtuple('Dict', 'keys values')
List = namedtuple('List', 'values')
Set = namedtuple('Set', 'elts')
Tuple = namedtuple('Tuple', 'elts')
String = namedtuple('String', 'value')
Assignment = namedtuple('Assignment', 'targets value')
FunctionDef = namedtuple('FunctionDef', 'name args body decorators returns')
Pass = namedtuple('Pass', '')
Ellipsis_ = namedtuple('Ellipsis_', '')
None_ = namedtuple('None_', '')
Del = namedtuple('Del', '')
Not = namedtuple('Not', 'expression')
Continue = namedtuple('Continue', '')
Assert = namedtuple('Assert', 'test msg')
Import = namedtuple('Import', 'names')
ImportFrom = namedtuple('ImportFrom', 'module names level')
Yield = namedtuple('Yield', 'expr')
YieldFrom = namedtuple('YieldFrom', 'expr')
Break = namedtuple('Break', '')
Return = namedtuple('Return', 'value')
Nonlocal = namedtuple('Nonlocal', 'names')
Global = namedtuple('Global', 'names')
Raise = namedtuple('Raise', 'exc cause')
LambdaDef = namedtuple('LambdaDef', 'args body')
Compare = namedtuple('Compare', 'left ops comparators')
If = namedtuple('If', 'test body or_else')
IfExp = namedtuple('IfExp', 'test body or_else')
While = namedtuple('While', 'test body or_else')
For = namedtuple('For', 'target iter body or_else')
ClassDef = namedtuple('ClassDef', 'name bases keywords body decorators')
Attribute = namedtuple('Attribute', 'value attr')
Subscript = namedtuple('Subscript', 'value slice')
Call = namedtuple('Call', 'func args keywords')
Arg = namedtuple('Arg', 'arg annotation')
Arguments = namedtuple('Arguments', 'args vararg kwonlyargs kw_defaults kwarg defaults')
BinOp = namedtuple('BinOp', 'left op right')
UnaryOp = namedtuple('UnaryOp', 'op operand')
BoolOp = namedtuple('BoolOp', 'values')
With = namedtuple('With', 'items body')
Expr = namedtuple('Expr', 'exp')
AugAssign = namedtuple('Augassign', 'target op value')

# arg=None for **kwargs
Keyword = namedtuple('Keyword', 'arg value')
Starred = namedtuple('Starred', 'value')
Name = namedtuple('Name', 'id')

_CompFor = namedtuple('CompFor', 'exprs or_test iterable')
_CompIf = namedtuple('CompIf', 'cond oppt')