file_input: (type | NEWLINE)* ENDMARKER
type: 'Type' NAME ':' suite

suite: NEWLINE INDENT (body_stmt|NEWLINE)+ DEDENT

body_stmt: stmt | block

stmt: declaration_stmt

# declaration stmts
declaration_stmt: default_decl_stmt | required_decl_stmt

default_decl_stmt: (enum ['=' STRING+] |
              integer ['=' NUMBER] |
              string ['=' STRING+] |
              bool ['=' ('True' | 'False')] |
              other ['=' py_expr_stmt]) NEWLINE
required_decl_stmt: '*' (string | enum | integer | bool | other) NEWLINE

# type declarations
enum: 'Enum' NAME '(' STRING (',' STRING)+ ')'
integer: 'Integer' NAME
string: 'String' NAME
bool: 'Bool' NAME
other: NAME NAME

# block stmts
block: form_block | validate_block

form_block: 'form' ':' block_suite
validate_block: 'validate' ':' block_suite

block_suite: py_suite | if_stmt_inline
if_stmt_inline: 'if' py_test ':' py_simple_stmt
